import 'package:flutter/material.dart';
import 'package:untitled/main.dart';
import 'package:untitled/quran/suranameitem.dart';

class qurantab extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final List<String> suranames = [
      "الفاتحه",
      "البقرة",
      "آل عمران",
      "النساء",
      "المائدة",
      "الأنعام",
      "الأعراف",
      "الأنفال",
      "التوبة",
      "يونس",
      "هود",
      "يوسف",
      "الرعد",
      "إبراهيم",
      "الحجر",
      "النحل",
      "الإسراء",
      "الكهف",
      "مريم",
      "طه",
      "الأنبياء",
      "الحج",
      "المؤمنون",
      "النّور",
      "الفرقان",
      "الشعراء",
      "النّمل",
      "القصص",
      "العنكبوت",
      "الرّوم",
      "لقمان",
      "السجدة",
      "الأحزاب",
      "سبأ",
      "فاطر",
      "يس",
      "الصافات",
      "ص",
      "الزمر",
      "غافر",
      "فصّلت",
      "الشورى",
      "الزخرف",
      "الدّخان",
      "الجاثية",
      "الأحقاف",
      "محمد",
      "الفتح",
      "الحجرات",
      "ق",
      "الذاريات",
      "الطور",
      "النجم",
      "القمر",
      "الرحمن",
      "الواقعة",
      "الحديد",
      "المجادلة",
      "الحشر",
      "الممتحنة",
      "الصف",
      "الجمعة",
      "المنافقون",
      "التغابن",
      "الطلاق",
      "التحريم",
      "الملك",
      "القلم",
      "الحاقة",
      "المعارج",
      "نوح",
      "الجن",
      "المزّمّل",
      "المدّثر",
      "القيامة",
      "الإنسان",
      "المرسلات",
      "النبأ",
      "النازعات",
      "عبس",
      "التكوير",
      "الإنفطار",
      "المطفّفين",
      "الإنشقاق",
      "البروج",
      "الطارق",
      "الأعلى",
      "الغاشية",
      "الفجر",
      "البلد",
      "الشمس",
      "الليل",
      "الضحى",
      "الشرح",
      "التين",
      "العلق",
      "القدر",
      "البينة",
      "الزلزلة",
      "العاديات",
      "القارعة",
      "التكاثر",
      "العصر",
      "الهمزة",
      "الفيل",
      "قريش",
      "الماعون",
      "الكوثر",
      "الكافرون",
      "النصر",
      "المسد",
      "الإخلاص",
      "الفلق",
      "الناس"
    ];
    return Column(
      crossAxisAlignment: CrossAxisAlignment.center,
      children: [
        Expanded(
            flex: 1, child: Image.asset('assets/images/top_icon_logo.png')),
        Container(
          height: 1,
          width: double.infinity,
          color: Mythemedata.primarycolor,
        ),
        Padding(
          padding: const EdgeInsets.all(8.0),
          child: Text(
            'sura name',
            style: TextStyle(fontSize: 25),
          ),
        ),
        Container(
          height: 1,
          width: double.infinity,
          color: Mythemedata.primarycolor,
        ),
        Expanded(
          flex: 4,
          child: ListView.separated(
            separatorBuilder: (buildContext, index) {
              return Container(
                margin: EdgeInsets.symmetric(horizontal: 12),
                height: 1,
                width: double.infinity,
                color: Mythemedata.primarycolor,
              );
            },
            itemBuilder: (buildContext, index) {
              return SuraNameItem(suranames[index], index);
            },
            itemCount: suranames.length,
          ),
        )
      ],
    );
  }
}
